import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UploadButton from "@/components/ui/upload-button";
import LayoutSwitcher from "@/components/ui/layout-switcher";
import ImageRefreshListener from "@/components/imageRefreshListener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ImageRefreshListener />
        <div className="flex w-full justify-center items-center px-5 pt-5">
          <div className="flex flex-col">
          <div className="flex justify-between items-center pb-4 pt-3 border-b">
            <LayoutSwitcher />
            <p className="text-sm">photos</p>
            <UploadButton />
          </div>
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
